id = com.adamderraz.games
name = gameshall
mainURL = https://stellular-biscotti-9570a1.netlify.app/
deeplink = 
icon = icon-512.png
scripts = *.js

allowSubdomains = true
requireDoubleBackToExit = true

enableExternalLinks = true
openExternalLinksInBrowser = true
confirmOpenInBrowser = true

MediaPlaybackRequiresUserGesture = false
DebugWebView = false
